---
apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-ids
spec:
  template:
    metadata:
      labels:
        name: scraper-ids
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - gu14.sciclone.wm.edu
                      - d3i01.sciclone.wm.edu
      containers:
        - name: scraper-ids
          image: ghcr.io/wmgeolab/get_project_ids:latest
          securityContext:
            runAsGroup: 50036
          volumeMounts:
            - name: scopenfs-scopedata
              mountPath: /scope/scope-data
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
          env:
            - name: OUTPUT_DIR
              value: "/scope/scope-data/gef/"
            - name: RATE_LIMIT
              value: "125"
            - name: BATCH_SIZE
              value: "500"
            - name: USE_FILE_TIMESTAMPS
              value: "false"
      imagePullSecrets:
        - name: github-registry-secret
      volumes:
        - name: scopenfs-scopedata
          nfs:
            server: 128.239.59.144
            path: /sciclone/geograd/scope/scope-data
      restartPolicy: OnFailure
