# Autoscaler deployment with environment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-autoscaler
  template:
    metadata:
      labels:
        app: vllm-autoscaler
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: autoscaler
          image: ghcr.io/wmgeolab/k8s-autoscaler:latest # Update this to your image
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 50036
            runAsUser: 237827
            # runAsNonRoot: true
          volumeMounts:
            - name: kube-config
              mountPath: /app/.kube
              readOnly: true
          resources:
            requests:
              memory: "128Mi" # Increased slightly for Python runtime
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 8000
          env:
            - name: KUBECONFIG
              value: /app/.kube/config
            - name: UVICORN_LOG_LEVEL
              value: "debug"
            - name: LOG_LEVEL
              value: "debug"
            - name: VLLM_SERVICE_HOST
              value: "vllm-svc"
            - name: VLLM_SERVICE_PORT
              value: "8000"
            - name: INACTIVITY_TIMEOUT
              value: "900"
            - name: ACTIVATION_TIMEOUT
              value: "120"
            - name: VLLM_DEPLOYMENT_NAME
              value: "vllm"
            - name: KUBERNETES_NAMESPACE
              value: "scope-dsmr"
            - name: PROXY_TIMEOUT # New setting for HTTP client timeout
              value: "30.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: kube-config
          secret:
            secretName: kube-certs
---
# Service for the autoscaler
apiVersion: v1
kind: Service
metadata:
  name: vllm-autoscaler-service
spec:
  selector:
    app: vllm-autoscaler
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
