apiVersion: v1
kind: Pod
metadata:
  name: alpine-tools
  labels:
    app: alpine-tools
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c", "apk add --no-cache nano curl && sleep infinity"]
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.2"
          memory: "128Mi"
