apiVersion: v1
kind: Pod
metadata:
  name: sawyer-deb
spec:
  containers:
    - image: debian:bookworm
      volumeMounts:
        - name: scopenfs
          mountPath: /scope # Any path you want to mount to.
      command:
        - /bin/sh
        - -c
        - |
          apt-get update &&
          apt-get install -y nano curl &&
          apt-get clean &&
          sleep 604800
      imagePullPolicy: IfNotPresent
      name: container-name
      resources:
        limits:
          cpu: 2 # Total 32 cores.
      securityContext:
        runAsUser: 237827
        runAsGroup: 50036
  volumes:
    - name: scopenfs
      nfs:
        server: 128.239.59.144 # NFS Server address.
        path: /sciclone/geograd/scope
