---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  labels:
    app: ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api
          image: ghcr.io/wmgeolab/ml-api:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: scopenfs
              mountPath: /scope # Any path you want to mount to.
          env:
            # Logs
            - name: LOGLEVEL
              value: "DEBUG"
            - name: UVICORN_LOGLEVEL
              value: "info"

            # Scope
            - name: SCOPE_BACKEND_URL
              value: "http://scope-backend-svc:8000" # TODO not sure if this is correct

            # Qdrant
            - name: QDRANT_URL
              value: "http://qdrant-svc:6333"
            - name: QDRANT_COLLECTION_NAME
              value: "scope-gef"

            # VLLM/TEI
            - name: VLLM_URL
              value: "http://vllm-qwen2-5-svc:8001/v1"
            - name: VLLM_MODEL_NAME
              value: "Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4"
            - name: TEI_URL
              value: "http://text-embedding-svc:8080"
            - name: LLM_CONTEXT_WINDOW
              value: "16384"
            - name: LLM_NUM_OUTPUT
              value: "8192"

            # Ingestion
            - name: DATA_BASE_DIR
              value: "/scope/scope-data/gef/output"
            - name: PIPELINE_PERSIST
              value: "true"
            - name: PIPELINE_PERSIST_PATH
              value: "/scope/k8s-storage/ml-api/ingestion"
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
            limits:
              cpu: "6"
              memory: 6Gi
          securityContext:
            runAsGroup: 50036
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: github-registry-secret
      volumes:
        - name: scopenfs
          nfs:
            server: 128.239.59.144 # NFS Server address.
            path: /sciclone/geograd/scope

---
apiVersion: v1
kind: Service
metadata:
  name: ml-api-svc
spec:
  selector:
    app: ml-api
  ports:
    - name: service-port
      port: 8000
      targetPort: 8000
  type: ClusterIP
