apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-1b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-3-1b
  template:
    metadata:
      labels:
        app: llama-3-1b
    spec:
      containers:
        - name: llama-3-1b
          image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            [
              "vllm serve meta-llama/Llama-3.2-1B-Instruct --trust-remote-code --enable-chunked-prefill --max_num_batched_tokens 1024",
            ]
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "10"
              memory: "16Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 6G
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
          securityContext:
            runAsUser: 237827
            runAsGroup: 50036
      volumes:
        - name: cache-volume
          nfs:
            server: 128.239.59.144
            path: /sciclone/geograd/scope/vllm/cache
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: llama-3-1b-service
spec:
  selector:
    app: llama-3-1b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
