apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm-container
          image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            [
              "vllm serve meta-llama/Meta-Llama-3-8B-Instruct --trust-remote-code --enable-chunked-prefill --max_num_batched_tokens 1024",
            ]
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "10"
              memory: "16Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 6G
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: model-volume
              mountPath: /models
            - name: cache-volume
              mountPath: /cache
          env:
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
          securityContext:
            runAsUser: 237827
            runAsGroup: 50036
      volumes:
        - name: model-volume
          nfs:
            server: 128.239.59.144
            path: /sciclone/geograd/scope/vllm/models
        - name: cache-volume
          nfs:
            server: 128.239.59.144
            path: /sciclone/geograd/scope/vllm/cache

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: vllm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
