apiVersion: v1
kind: Pod
metadata:
  name: deb-tools
spec:
  containers:
    - image: debian:bookworm
      volumeMounts:
        - name: scopenfs
          mountPath: /scope # Any path you want to mount to.
      command: ["/bin/bash", "-c"]
      args:
        [
          "apt-get update && apt-get install -y nano curl make jq && sleep infinity",
        ]
      imagePullPolicy: IfNotPresent
      name: debian
      resources:
        limits:
          cpu: "2" # Total 32 cores.
          memory: "4Gi"
        requests:
          cpu: "2" # Total 32 cores.
          memory: "4Gi"
      securityContext:
        runAsGroup: 50036
  volumes:
    - name: scopenfs
      nfs:
        server: 128.239.59.144 # NFS Server address.
        path: /sciclone/geograd/scope
