apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-services-config
data:
  services.yaml: |
    services:
      internvl:
        deployment_name: lmdeploy-internvl
        selector_label: app
        selector_value: lmdeploy-internvl
        service_host: lmdeploy-internvl-svc
        service_port: 23333
        namespace: scope-dsmr
        inactivity_timeout: 900
        activation_timeout: 120

      qwen2.5vl:
        deployment_name: vllm-qwen2-5vl
        selector_label: app
        selector_value: vllm-qwen2-5vl
        service_host: vllm-svc
        service_port: 8000
        namespace: scope-dsmr
        inactivity_timeout: 900
        activation_timeout: 120
      
      vllm-qwen2-5:
        deployment_name: vllm-qwen2-5
        selector_label: app
        selector_value: vllm-qwen2-5
        service_host: vllm-qwen2-5-svc
        service_port: 8001
        namespace: scope-dsmr
        inactivity_timeout: 900
        activation_timeout: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: autoscaler
          image: ghcr.io/wmgeolab/k8s-autoscaler:latest # Update this to your image
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 50036
            runAsUser: 237827
            # runAsNonRoot: true
          volumeMounts:
            - name: kube-config
              mountPath: /app/.kube
              readOnly: true
            - name: autoscaler-services-config
              mountPath: /app/services.yaml
              subPath: services.yaml
          resources:
            requests:
              memory: "128Mi" # Increased slightly for Python runtime
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 8000
          env:
            - name: KUBECONFIG
              value: /app/.kube/config
            - name: UVICORN_LOG_LEVEL
              value: "debug"
            - name: LOG_LEVEL
              value: "debug"
            # - name: DEFAULT_INACTIVITY_TIMEOUT
            #   value: "900"
            # - name: DEFAULT_ACTIVATION_TIMEOUT
            #   value: "120"
            - name: DEFAULT_KUBERNETES_NAMESPACE
              value: "scope-dsmr"
            - name: SERVICES_CONFIG_PATH
              value: "/app/services.yaml"
            - name: KUBERNETES_NAMESPACE
              value: "scope-dsmr"
            - name: PROXY_TIMEOUT # New setting for HTTP client timeout
              value: "30.0"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: kube-config
          secret:
            secretName: kube-certs
        - name: autoscaler-services-config
          configMap:
            name: autoscaler-services-config
            items:
              - key: services.yaml
                path: services.yaml
---
# Service for the autoscaler
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-service
spec:
  selector:
    app: autoscaler
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
