name: Mirroring

on: [push, delete]

jobs:
    mirror-to-gitlab:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Mirror
              uses: pixta-dev/repository-mirroring-action@v1.1.1
              with:
                target_repo_url: git@code.wm.edu:data-science/geolab/scope-ml.git
                ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

                